"""initial_schema

Revision ID: 23f2b34a851d
Revises: 
Create Date: 2026-04-19 15:17:06.069395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f2b34a851d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    wind_direction_enum = sa.Enum('N', 'S', 'E', 'W', 'NW', 'SW', 'NE', 'SE', name='winddirection')
    op.create_table('celestial_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.Column('sunset', sa.Time(), nullable=True),
    sa.Column('moonrise', sa.Time(), nullable=True),
    sa.Column('moonset', sa.Time(), nullable=True),
    sa.Column('moon_phase', sa.String(length=255), nullable=True),
    sa.Column('moon_illumination', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length =255), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('wind_degree', sa.Integer(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Enum('N', 'S', 'E', 'W', 'NW', 'SW', 'NE', 'SE', name='winddirection'), nullable=True),
    sa.Column('celestial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['celestial_id'], ['celestial_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    op.drop_table('celestial_events')
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        sa.Enum(name='winddirection').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
