"""add_should_go_outside_column

Revision ID: d7930361946a
Revises: 23f2b34a851d
Create Date: 2026-04-19 15:35:05.957143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7930361946a'
down_revision: Union[str, None] = '23f2b34a851d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celestial_events', sa.Column('should_go_outside', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('celestial_events', 'should_go_outside')
    # ### end Alembic commands ###
